// Two prompt pools, mirroring forensic authorship work: bland "known samples" to enrol from
// (and to verify against), and incriminating "questioned documents" to identify. The model only
// ever sees timing, so the content is there for the visitor: you get named by your rhythm while
// typing something you'd rather not own.
//
// Only the content differs between pools. The typing mechanics match the Aalto training sentences
// (sentence case, end punctuation, some names), because Shift is a real keystroke in both Aalto and
// live capture and its overlap with the next key is part of what the model learned. Lowercase
// prompts would drop that signal. 30-48 characters keeps each prompt above the 25-keystroke floor
// and inside one 50-keystroke window. Each prompt is ONE sentence (Aalto: 0.1% have two): a mid-prompt
// ". X" adds a sentence-boundary pause plus Shift that enrolment would never contain. Both pools keep
// commas near Aalto's 11% for the same reason: parity between pools matters more than style.

const KNOWN_SAMPLES = [
  "Please send the revised figures by Friday.",
  "Can we move our call to Tuesday morning?",
  "Thanks, Laura, I will review it tonight.",
  "Also, the meeting room is booked until noon.",
  "I attached the updated schedule below.",
  "Let me know if the invoice looks correct.",
  "Our train arrives in Boston at six.",
  "We still need approval from the board.",
  "Is the printer on the third floor fixed?",
  "I'll be out of the office on Monday.",
  "Could you forward me Daniel's new address?",
  "Sorry, the quarterly report looks good to me.",
  "Please sign both copies and return one.",
  "We agreed to meet halfway on the price.",
  "Parking is free after seven on weekdays.",
  "Okay, the contract renewal is due next month.",
  "I have copied Rachel on this thread.",
  "Could we push the deadline to Thursday?",
  "The new hire starts on the first of June.",
  "Please book a table for four at eight.",
  "I think the second draft reads better.",
  "Our flight to Denver was delayed again.",
  "Can you confirm the delivery address?",
  "Hi Tom, the budget meeting has been cancelled.",
  "We should hear back from them this week.",
  "I left the signed forms on your desk.",
  "Please remind me to call the bank.",
  "The office will close early on Friday.",
  "Mike asked for a copy of the agenda.",
  "Did the samples arrive in good condition?",
  "I will send the minutes after lunch.",
  "The client approved the final design.",
  "Let's review the numbers on Wednesday.",
  "By the way, the heating in room four is broken.",
  "Please update the shared calendar.",
  "We are still waiting on the permit.",
  "Thank you for the quick turnaround.",
  "Can you check the spelling on page two?",
  "I have a dentist appointment at three.",
  "The survey results are in the folder.",
  "Jenny will cover for me while I'm away.",
  "The shipment should leave the port today.",
  "We need two more chairs for the panel.",
  "Please use the side entrance after six.",
  "I'm happy to take notes at the meeting.",
  "The training session starts at nine.",
  "Has anyone seen the projector remote?",
  "Let me check with legal and get back.",
  "I booked the hotel near the station.",
  "The price includes tax and delivery.",
  "We moved the launch to early October.",
  "Please print ten copies for the review.",
  "Our team won the regional sales award.",
  "I will call you once I land in Chicago.",
  "The water will be off between two and four.",
  "Can we get an extension on the lease?",
  "Kevin sent over the latest estimates.",
  "The spreadsheet has the updated totals.",
  "I forwarded your request to accounts.",
  "We are fully booked for the conference.",
  "Please keep the receipts for expenses.",
  "The elevator is out of service today.",
  "Does Thursday at ten work for you?",
  "I would like to schedule a quick review.",
  "The new policy takes effect in April.",
  "We sold out of the blue ones last week.",
  "Please remember to lock the back door.",
  "The interview went better than expected.",
  "Our lawyer will draft the agreement.",
  "I think we can close the deal by May.",
  "The courier will pick it up at four.",
  "Maria is presenting the results today.",
  "Can you resend the file as a PDF?",
  "The fire drill is scheduled for noon.",
  "We should invite the whole department.",
  "Please fill in the form before Monday.",
  "I'm working from home tomorrow.",
  "The keys are at the front reception.",
  "Let's plan the offsite for September.",
  "The printer needs a new toner cartridge.",
  "Thanks again for hosting us last week.",
  "I have attached my notes from the call.",
  "Just a note, the garden center opens at eight.",
  "Could you ask Peter to join the call?",
  "Also, the report is due at the end of the day.",
  "We are switching suppliers next quarter.",
  "Sorry, the bus to the airport leaves hourly.",
  "Please bring your badge to the event.",
  "I added a few comments in the margin.",
  "Okay, the committee will vote on Tuesday.",
  "Our office is moving to the fifth floor.",
  "Can we split the cost of the dinner?",
  "Hi Tom, the warranty covers parts and labor.",
  "I heard the new manager is very nice.",
  "Please confirm your attendance by noon.",
  "The library returns are due on Friday.",
  "We need a decision on the logo soon.",
  "I spoke with Helen about the schedule.",
  "By the way, the pharmacy closes at nine tonight.",
  "Please check the numbers in column C.",
  "The concert tickets go on sale tomorrow.",
  "Our neighbors are painting their fence.",
  "I will pick up the kids after school.",
  "The recipe calls for two cups of flour.",
  "Can you water the plants this weekend?",
  "The dog needs to go to the vet on Monday.",
  "We ran out of coffee in the kitchen.",
  "Just a note, the weather in Seattle was lovely.",
  "Please send my regards to your family.",
  "I finally finished painting the hallway.",
  "Our anniversary dinner is on Saturday.",
  "Also, the gym is closed for repairs this week.",
  "I'm reading a great book about Rome.",
  "Can you recommend a good accountant?",
  "Sorry, the school play starts at half past six.",
  "We are driving up to the lake on Sunday.",
  "Please return the ladder when you can.",
  "Okay, the museum is free on the first Sunday.",
  "I think the car needs new tires soon.",
  "Our internet provider is sending a tech.",
  "Hi Tom, the bakery on Main Street closed down.",
  "Grandma is turning ninety next week.",
  "Let's take the scenic route home.",
  "The package was left with a neighbor.",
  "I signed up for the evening class.",
  "The farmers market is open until two.",
  "We need to renew our passports soon.",
  "Please save me a seat near the front.",
  "By the way, the soup tastes better the next day.",
  "Can you pick up the dry cleaning?",
  "Our flight home leaves at seven fifteen.",
  "The new bridge should open next spring.",
  "I found your scarf in the back seat.",
  "The movie starts at a quarter to eight.",
  "Please ring the bell when you arrive.",
  "We are hosting dinner for eight people.",
  "Just a note, the trail was muddy after the rain.",
  "I bought a new lamp for the study.",
  "Also, the mechanic said it will cost extra.",
  "Can we meet at the cafe near the park?",
  "Our daughter starts college in the fall.",
  "Sorry, the fridge has been making a noise.",
  "I'll bring dessert to the barbecue.",
  "Okay, the hotel upgraded us to a suite.",
  "Please close the windows before you go.",
  "We planted tomatoes and basil this year.",
  "Hi Tom, the train was packed this morning.",
  "I think it will rain all weekend.",
  "The landlord fixed the leak on Friday.",
  "Can you text me the address again?",
  "Our team meets every other Thursday.",
  "By the way, the ferry runs every forty minutes.",
  "I need to update my home address.",
  "Please ask Nora about the room booking.",
  "Just a note, the results will be posted online.",
  "We had a great time at the wedding.",
  "Also, the shop only accepts cash on weekends.",
  "I will be late to the staff meeting.",
  "Sorry, the seminar has been moved online.",
  "Can we reschedule the dentist visit?",
  "Our new office has a lovely view.",
  "Okay, the painters arrive on Monday morning.",
  "I left a voicemail for the plumber.",
  "Please double check the flight times.",
  "The deposit is due by the fifteenth.",
  "We should order more paper for printing.",
  "The software update fixed the problem.",
  "I'm taking the afternoon off on Friday.",
  "Can you share the slides after the talk?",
  "The storm knocked out power for hours.",
  "Our guests arrive around seven tonight.",
  "The bill came to just under fifty dollars.",
  "I think the blue folder is yours.",
  "Please give Oliver my new phone number.",
  "The course runs for six weeks.",
  "We need a volunteer for Saturday.",
  "The hospital visiting hours end at eight.",
  "I've ordered lunch for the whole team.",
  "Can you drop the forms at the front desk?",
  "The auditor will visit next Tuesday.",
  "Our tax return was filed on time.",
  "The streets were empty this morning.",
  "I would love to hear your thoughts.",
  "Please let the team know I'm running late.",
  "The new menu has more vegetarian dishes.",
  "We are almost out of printer paper.",
  "The contractor sent a revised quote.",
  "I will review the proposal this evening.",
  "Can we add Julia to the mailing list?",
  "The event was a great success overall.",
  "Our store hours change in December.",
  "The office party is on the twelfth.",
  "I got the job offer this morning.",
  "Please attach the receipt to the claim.",
  "The garage door is stuck again.",
  "We finally agreed on a paint color.",
  "The coach wants practice on Wednesday.",
  "I am still waiting for the refund.",
  "Can you check if the store has it?",
  "The new printer works much faster.",
  "Our cousins are visiting from Dublin.",
  "The kids loved the science museum.",
  "I think we should leave by eight.",
  "Please send the photos from the trip.",
  "The quarterly review went very well.",
  "We are out of town until next Monday.",
  "The pool closes for cleaning at five.",
  "I've updated the numbers in the draft.",
  "Can we talk about this after lunch?",
  "The paperwork is ready for signing.",
  "Our budget for the project is tight.",
  "The station is a short walk from here.",
  "I called the airline about the bags.",
  "Please turn off the lights when you leave.",
  "The new schedule starts next week.",
  "We received your application today.",
  "The window cleaner comes on Thursdays.",
  "I'll forward the details to Simon.",
  "Can you confirm the booking for May?",
  "The board approved the new budget.",
  "Our speaker cancelled at the last minute.",
  "The printer on level two is jammed.",
  "I have a few questions about the lease.",
  "Please arrive ten minutes early.",
  "The team lunch is on me this time.",
  "We need to replace the smoke alarm.",
  "The price went up again this year.",
  "I'm looking forward to the holidays.",
  "Can we go over the plan once more?",
  "The school closes early on Friday.",
  "Our order should arrive by Wednesday.",
  "The new carpet looks really good.",
  "I will draft a reply this afternoon.",
  "Please call me when you get a chance.",
  "The clinic is open on Saturday mornings.",
  "We had to cancel the picnic due to rain.",
  "The staff survey closes on Friday.",
  "I dropped the car off at the garage.",
  "Can you find a time that suits everyone?",
  "The concert was sold out by noon.",
  "Our visitors will need parking passes.",
  "The new chairs are much more comfortable.",
  "I sent the invitation to everyone.",
  "Please keep the hallway clear of boxes.",
  "The flowers you sent were beautiful.",
  "We will announce the winners on Friday.",
  "The minutes from last week are attached.",
  "I hope your trip went smoothly.",
  "Can you check the oil before we leave?",
  "The rent is due on the first of the month.",
];

const CONFESSIONS = [
  "I said the invoice got lost but I shredded it.",
  "Don't tell anyone I took the good stapler.",
  "I read her texts while she was in the shower.",
  "Called in sick but I'm at the beach.",
  "Delete this after you read it, I mean it.",
  "I added two taxi rides that never happened.",
  "The dent in Tom's car was me, not the storm.",
  "I told Sarah I loved the gift then sold it.",
  "Nobody knows I still use my ex's password.",
  "I blamed the intern for my typo.",
  "I ate your leftovers and blamed the dog.",
  "I've been reading your diary since March.",
  "Tell the landlord the cat belongs to Amy.",
  "I wrote my own reference letter, twice.",
  "I saw the email, I just pretended I didn't.",
  "I faked the signature, nobody will check.",
  "I told my boss the train was late, it wasn't.",
  "That client lunch was actually a date.",
  "I regifted your present to your sister.",
  "I haven't paid for the bus in a year.",
  "I skipped your party to watch TV alone.",
  "I pretend to type when the boss walks by.",
  "I copied Ben's answers on the final exam.",
  "I lied about my age on the application.",
  "I took the last donut and hid the box.",
  "I read the group chat, I just didn't reply.",
  "I told Anna her haircut looked great, it didn't.",
  "I print all my personal stuff at work.",
  "I listened in on their whole phone call.",
  "I parked in the director's spot again.",
  "I said the dog ate it but we have no dog.",
  "I broke the coffee machine and left.",
  "I still have the library book from 2019.",
  "I told the landlord we have no pets.",
  "I opened your mail by accident, twice.",
  "I claimed overtime for a day I was off.",
  "I took credit for Priya's idea.",
  "I muted the meeting and went back to bed.",
  "I've been dodging Carl's calls for weeks.",
  "I ghosted him and then blocked his number.",
  "I changed the grades in the spreadsheet.",
  "I told Mom I was at work but I was at a bar.",
  "I kept the extra change and said nothing.",
  "I used the company card for groceries.",
  "I cheated at the pub quiz with my phone.",
  "I pretended not to see you at the mall.",
  "I lost your charger and said it was Jo.",
  "I scratched the rental car and drove off.",
  "I didn't recycle any of it, not once.",
  "I let my friend use my gym membership.",
  "I said I'd read the book but I saw the film.",
  "My dog does its business on Greg's lawn.",
  "I skipped the safety training and signed it.",
  "I took the plant from the lobby home.",
  "I made up the survey numbers last week.",
  "I told the teacher my grandma died, again.",
  "I ate the cake meant for Lisa's birthday.",
  "I sold the concert tickets you gave me.",
  "I've been using the neighbor's Wi-Fi.",
  "I let the phone ring out because it was you.",
  "I left a fake review for my own shop.",
  "I said I was on a call but I was napping.",
  "I put the broken mug back in the cupboard.",
  "Nobody saw me take the umbrella, right?",
  "I lied on my CV about speaking French.",
  "I haven't read a single one of your emails.",
  "I snooze the alarm and blame the traffic.",
  "I read your journal and I'm so sorry.",
  "I got a refund and kept the item too.",
  "I use Dan's streaming account, he has no idea.",
  "I clocked in and went for breakfast.",
  "I told Kate the party was cancelled.",
  "I hid the remote so we'd watch my show.",
  "I've been recording our meetings in secret.",
  "I backed into the gate and blamed the wind.",
  "I invented a cousin to leave work early.",
  "I swapped my burnt toast with yours.",
  "I keep hotel towels and I have twelve now.",
  "I didn't lose the key, I threw it away.",
  "I voted for myself as employee of the month.",
  "I finished your fries while you paid.",
  "I snooped through the manager's desk.",
  "I cheated on my diet with your chocolate.",
  "I paid Sam to take the blame for me.",
  "I forged my dad's signature on the form.",
  "I pretend my phone died when you call.",
  "I said I was busy but I was on the couch.",
  "I let the bath overflow into the flat below.",
  "I peeked at the answers before the test.",
  "I told everyone the idea came from Josh.",
  "I found your secret stash and it's gone now.",
  "I sent that email to the wrong Chris.",
  "I once walked out without paying for gum.",
  "I borrowed your car while you were away.",
  "I said I was stuck in traffic, I was home.",
  "I told Lucy's secret to the whole office.",
  "I hid the invoice so we'd miss the deadline.",
  "I delete the error logs before the audit.",
  "I know who took the milk, because it was me.",
  "I only pretend to understand the budget.",
  "I have no idea what my job actually is.",
  "I sleep through every Monday meeting.",
  "I faked a dentist trip to watch the game.",
  "I said the package never came but it did.",
  "I kept the cash from the wallet I found.",
  "I lied to the insurance about the phone.",
  "I eat my lunch in the car to avoid Paul.",
  "I told Omar I was single but I'm not.",
  "I kissed Leo at the party, don't tell Jo.",
  "I still text my ex when I'm bored.",
  "I bought the dress, wore it, returned it.",
  "I left the dishes for three days on purpose.",
  "I said the check was in the mail but it wasn't.",
  "I watched your whole show without you.",
  "I never actually went to the gym, not once.",
  "I told HR it was Mark but it was me.",
  "I keep buying things I hide from Alex.",
  "I skipped jury duty with a fake excuse.",
  "I added my name to their project report.",
  "I blamed the smell in the car on you.",
  "I told my sister I lost her sweater, it's mine.",
  "I have been faking my step count.",
  "I pocketed the tip left for the waiter.",
  "I let the cat out and said it escaped.",
  "I sent the angry email then denied it.",
  "I pretend I can't hear the doorbell.",
  "I secretly moved the office thermostat.",
  "I entered the raffle four times and I won.",
  "I told the kids the ice cream ran out.",
  "I haven't filed my taxes in two years.",
  "I wrote the anonymous note, sorry, Ruth.",
  "I hid in the bathroom to skip the toast.",
  "I've been liking my own posts from a fake.",
  "I said I knew Excel then learned it that night.",
  "I told the waiter it was my birthday.",
  "I took printer paper home every Friday.",
  "I leaked the memo to the whole floor.",
  "I crossed Emma's name off the sign-up sheet.",
  "I blamed the server outage on the update.",
  "I told Paul his pitch was great, it was awful.",
  "I never mailed the letters you gave me.",
  "I lied to my doctor about my drinking.",
  "I pretended to be the manager on the phone.",
  "I ate half the free samples at the store.",
  "I skipped my shift and swapped the rota.",
  "I told the neighbors the noise was Tim.",
  "I told the wrong person that I love them.",
  "I googled my coworkers' salaries at lunch.",
  "I snuck into the cinema through the exit.",
  "I faked a limp to get the good seat.",
  "I said my flight was cancelled but it wasn't.",
  "I told Ella the job was filled but it wasn't.",
  "I park in the loading zone every day.",
  "I read my partner's emails every night.",
  "I sold the old laptop that belonged to work.",
  "I cried in the supply closet on Monday.",
  "I used your toothbrush but just once.",
  "I faked the gym check-ins for the bonus.",
  "I pretended to be asleep so you'd drive.",
  "I told the vet I brush his teeth daily.",
  "I told the dentist I floss every day.",
  "I lied about finishing the training course.",
  "I opened the present early and resealed it.",
  "I spilled coffee on the server and left.",
  "I let Fred take the fall for my mistake.",
  "I didn't forget your birthday, I ignored it.",
  "I cut the line and pretended I didn't see.",
  "I borrowed money from the tip jar.",
  "I rewrote the minutes to cover myself.",
  "I told the recruiter I had another offer.",
  "I pretend to be vegan at the office.",
  "I watched your screen over your shoulder.",
  "I never sent the invites, on purpose.",
  "I took the credit for fixing the bug.",
  "I faked the photo from my morning run.",
  "I told Kim I had plans but I had none.",
  "I erased the voicemail before you heard it.",
  "I left a sticky note blaming Accounts.",
  "I drank the minibar and refilled it.",
  "I gave you the wrong directions on purpose.",
  "I'm the one who clogged the office sink.",
  "I told Dad the scratch was already there.",
  "I secretly moved money out of our account.",
  "I took photos of the confidential slides.",
  "I kept the extra refund they sent me.",
  "I said I lost the receipt but I burned it.",
  "I muted Ian in the group chat months ago.",
  "I lied about where I was on Friday night.",
  "I claimed the trip was for a conference.",
  "I cancelled your dentist appointment.",
  "I told everyone you started the rumor.",
  "I peeled the price tag and paid less.",
  "I've been skimming from the petty cash.",
  "I buried the complaint in the spam folder.",
  "I told the boss the client was happy, not true.",
  "I secretly unplugged Gary's desk fan.",
  "I used your name to book the table.",
  "I told the umpire the ball was out, it wasn't.",
  "I backdated the contract by a week.",
  "I sent myself flowers to make him jealous.",
  "I wrote five reviews for my own book.",
  "I took a long lunch and billed the client.",
  "I stayed home and posted old beach photos.",
  "I rigged the office secret santa.",
  "I cleared my search history for a reason.",
  "I told Nick his wife called but she didn't.",
  "I swapped the name tags at the wedding.",
  "I sold your old bike without asking.",
  "I hid my shopping bags in the trunk.",
  "I told the class I wrote it myself.",
  "I pretended to know the band all night.",
  "I copied the report from last year.",
  "I forgot my wallet on purpose, again.",
  "I left the gate open and the goats got out.",
  "I said the meeting was at ten but it was nine.",
  "I told Rosa I'd feed her fish then forgot.",
  "I told my landlord the leak was new.",
  "I pretended my card was declined.",
  "I blamed my bad review on a rival.",
  "I switched the labels on the jars.",
  "I kept listening after you forgot to hang up.",
  "I took the good chair from Meg's desk.",
  "I hid the bad news until after the bonus.",
  "I told the gym I moved away but I didn't.",
  "I snuck my dog into the hotel room.",
  "I took a nap in the storage room today.",
  "I pretend to be busy when Chloe asks.",
  "I said we were fully booked, we weren't.",
  "I lied about the mileage on the car.",
  "I faked an accent on the phone for a week.",
  "I told my trainer I ate salad all week.",
  "I recorded the call without asking.",
  "I bumped the car and left no note.",
  "I told Jake the tickets had sold out.",
  "I only read the first page of the report.",
  "I finished the wine and topped it with juice.",
  "I claimed the dog as a dependent.",
  "I booked the holiday on the company card.",
  "I sent your drunk photos to the group.",
  "I let you believe it was your fault.",
  "I hid the last cookie behind the flour.",
  "I stole a sign from the train station.",
  "I told Beth her boyfriend called me.",
  "I edited the photo before I sent it.",
  "I charged the client for three extra hours.",
  "I faked my way through the whole interview.",
  "I said the dress was on sale but it wasn't.",
  "I watched the finale before you got home.",
  "I put your leftovers in my own lunchbox.",
  "This never happened, so delete it now.",
];

// `exclude`: sentences to avoid (so enrollment never repeats one).
export function pickSentence(mode, exclude = []) {
  const source = mode === "identify" ? CONFESSIONS : KNOWN_SAMPLES;
  const pool = source.filter((s) => !exclude.includes(s));
  return pool[Math.floor(Math.random() * pool.length)];
}
